import { TooltipProvider } from '../vendor/shadcn/ui/tooltip';
import { lazy, type ComponentType } from 'react';
import { Toaster } from '../vendor/shadcn/ui/sonner';
import { DirectionProvider } from '../vendor/shadcn/ui/direction';
import { PreviewControlsProvider } from '../vendor/rare/components/preview/PreviewControls';
import { cn } from '../vendor/rare/lib/utils';
const Demo0=lazy(()=>import('../vendor/interior/demos/hold-to-confirm').then(m=>({default:m.HoldToConfirmDemo})));
const Demo1=lazy(()=>import('../vendor/interior/demos/loading-button').then(m=>({default:m.LoadingButtonDemo})));
const Demo2=lazy(()=>import('../vendor/interior/demos/ripple').then(m=>({default:m.RippleDemo})));
const Demo3=lazy(()=>import('../vendor/interior/demos/floating-label').then(m=>({default:m.FloatingLabelDemo})));
const Demo4=lazy(()=>import('../vendor/interior/demos/press-depth').then(m=>({default:m.PressDepthDemo})));
const Demo5=lazy(()=>import('../vendor/interior/demos/icon-morph').then(m=>({default:m.IconMorphDemo})));
const Demo6=lazy(()=>import('../vendor/interior/demos/like-burst').then(m=>({default:m.LikeBurstDemo})));
const Demo7=lazy(()=>import('../vendor/interior/demos/copy-button').then(m=>({default:m.CopyButtonDemo})));
const Demo8=lazy(()=>import('../vendor/interior/demos/password-strength').then(m=>({default:m.PasswordStrengthDemo})));
const Demo9=lazy(()=>import('../vendor/interior/demos/expanding-search').then(m=>({default:m.ExpandingSearchDemo})));
const Demo10=lazy(()=>import('../vendor/interior/demos/inline-validation').then(m=>({default:m.InlineValidationDemo})));
const Demo11=lazy(()=>import('../vendor/interior/demos/otp-input').then(m=>({default:m.OtpInputDemo})));
const Demo12=lazy(()=>import('../vendor/interior/demos/tag-input').then(m=>({default:m.TagInputDemo})));
const Demo13=lazy(()=>import('../vendor/interior/demos/progress-bar').then(m=>({default:m.ProgressBarDemo})));
const Demo14=lazy(()=>import('../vendor/interior/demos/skeleton-swap').then(m=>({default:m.SkeletonSwapDemo})));
const Demo15=lazy(()=>import('../vendor/interior/demos/load-more').then(m=>({default:m.LoadMoreDemo})));
const Demo16=lazy(()=>import('../vendor/interior/demos/task-steps').then(m=>({default:m.TaskStepsDemo})));
const Demo17=lazy(()=>import('../vendor/interior/demos/live-activity').then(m=>({default:m.LiveActivityDemo})));
const Demo18=lazy(()=>import('../vendor/interior/demos/collapsible-banner').then(m=>({default:m.CollapsibleBannerDemo})));
const Demo19=lazy(()=>import('../vendor/interior/demos/presence-avatars').then(m=>({default:m.PresenceAvatarsDemo})));
const Demo20=lazy(()=>import('../vendor/interior/demos/streaming-text').then(m=>({default:m.StreamingTextDemo})));
const Demo21=lazy(()=>import('../vendor/interior/demos/typing-indicator').then(m=>({default:m.TypingIndicatorDemo})));
const Demo22=lazy(()=>import('../vendor/interior/demos/modal').then(m=>({default:m.ModalDemo})));
const Demo23=lazy(()=>import('../vendor/interior/demos/new-items-pill').then(m=>({default:m.NewItemsPillDemo})));
const Demo24=lazy(()=>import('../vendor/interior/demos/context-menu').then(m=>({default:m.ContextMenuDemo})));
const Demo25=lazy(()=>import('../vendor/interior/demos/drawer').then(m=>({default:m.DrawerDemo})));
const Demo26=lazy(()=>import('../vendor/interior/demos/tooltip-group').then(m=>({default:m.TooltipGroupDemo})));
const Demo27=lazy(()=>import('../vendor/interior/demos/dropdown').then(m=>({default:m.DropdownDemo})));
const Demo28=lazy(()=>import('../vendor/interior/demos/command-palette').then(m=>({default:m.CommandPaletteDemo})));
const Demo29=lazy(()=>import('../vendor/interior/demos/popover').then(m=>({default:m.PopoverDemo})));
const Demo30=lazy(()=>import('../vendor/interior/demos/segmented-control').then(m=>({default:m.SegmentedControlDemo})));
const Demo31=lazy(()=>import('../vendor/interior/demos/tabs').then(m=>({default:m.TabsDemo})));
const Demo32=lazy(()=>import('../vendor/interior/demos/sticky-header').then(m=>({default:m.StickyHeaderDemo})));
const Demo33=lazy(()=>import('../vendor/interior/demos/tree-view').then(m=>({default:m.TreeViewDemo})));
const Demo34=lazy(()=>import('../vendor/interior/demos/pagination').then(m=>({default:m.PaginationDemo})));
const Demo35=lazy(()=>import('../vendor/interior/demos/reading-progress').then(m=>({default:m.ReadingProgressDemo})));
const Demo36=lazy(()=>import('../vendor/interior/demos/scroll-spy').then(m=>({default:m.ScrollSpyDemo})));
const Demo37=lazy(()=>import('../vendor/interior/demos/accordion').then(m=>({default:m.AccordionDemo})));
const Demo38=lazy(()=>import('../vendor/interior/demos/wizard-steps').then(m=>({default:m.WizardStepsDemo})));
const Demo39=lazy(()=>import('../vendor/interior/demos/snap-carousel').then(m=>({default:m.SnapCarouselDemo})));
const Demo40=lazy(()=>import('../vendor/interior/demos/filter-grid').then(m=>({default:m.FilterGridDemo})));
const Demo41=lazy(()=>import('../vendor/interior/demos/hide-on-scroll').then(m=>({default:m.HideOnScrollDemo})));
const Demo42=lazy(()=>import('../vendor/interior/demos/value-flash').then(m=>({default:m.ValueFlashDemo})));
const Demo43=lazy(()=>import('../vendor/interior/demos/reorder-list').then(m=>({default:m.ReorderListDemo})));
const Demo44=lazy(()=>import('../vendor/interior/demos/poll-results').then(m=>({default:m.PollResultsDemo})));
const Demo45=lazy(()=>import('../vendor/interior/demos/swipe-deck').then(m=>({default:m.SwipeDeckDemo})));
const Demo46=lazy(()=>import('../vendor/interior/demos/slider-detents').then(m=>({default:m.SliderDetentsDemo})));
const Demo47=lazy(()=>import('../vendor/interior/demos/sortable-table').then(m=>({default:m.SortableTableDemo})));
const Demo48=lazy(()=>import('../vendor/interior/demos/long-press').then(m=>({default:m.LongPressDemo})));
const Demo49=lazy(()=>import('../vendor/interior/demos/logo-marquee').then(m=>({default:m.LogoMarqueeDemo})));
const Demo50=lazy(()=>import('../vendor/interior/demos/blur-up-image').then(m=>({default:m.BlurUpImageDemo})));
const Demo51=lazy(()=>import('../vendor/interior/demos/lightbox').then(m=>({default:m.LightboxDemo})));
const Demo52=lazy(()=>import('../vendor/interior/demos/text-reveal').then(m=>({default:m.TextRevealDemo})));
const Demo53=lazy(()=>import('../vendor/rare/demos/folder-component').then(m=>({default:m.default})));
const Demo54=lazy(()=>import('../vendor/interior/demos/show-more').then(m=>({default:m.ShowMoreDemo})));
const Demo55=lazy(()=>import('../vendor/rare/demos/hook-sidebar').then(m=>({default:m.default})));
const Demo56=lazy(()=>import('../vendor/rare/demos/proximity-sidebar').then(m=>({default:m.default})));
const Demo57=lazy(()=>import('../vendor/rare/demos/fluid-orb').then(m=>({default:m.default})));
const Demo58=lazy(()=>import('../vendor/rare/demos/family-drawer').then(m=>({default:m.default})));
const Demo59=lazy(()=>import('../vendor/rare/demos/code-block').then(m=>({default:m.default})));
const Demo60=lazy(()=>import('../vendor/rare/demos/scroll-progress').then(m=>({default:m.default})));
const Demo61=lazy(()=>import('../vendor/rare/demos/duration-picker').then(m=>({default:m.default})));
const Demo62=lazy(()=>import('../vendor/rare/demos/bounce-sidebar').then(m=>({default:m.default})));
const Demo63=lazy(()=>import('../vendor/rare/demos/gravity-letters').then(m=>({default:m.default})));
const Demo64=lazy(()=>import('../vendor/rare/demos/emoji-reaction').then(m=>({default:m.default})));
const Demo65=lazy(()=>import('../vendor/rare/demos/notification-bell').then(m=>({default:m.default})));
const Demo66=lazy(()=>import('../vendor/rare/demos/otp-input').then(m=>({default:m.default})));
const Demo67=lazy(()=>import('../vendor/rare/demos/gooey-nav').then(m=>({default:m.default})));
const Demo68=lazy(()=>import('../vendor/rare/demos/step-player').then(m=>({default:m.default})));
const Demo69=lazy(()=>import('../vendor/rare/demos/github-activity').then(m=>({default:m.default})));
const Demo70=lazy(()=>import('../vendor/rare/demos/grid-reveal').then(m=>({default:m.default})));
const Demo71=lazy(()=>import('../vendor/rare/demos/delete-button').then(m=>({default:m.default})));
const Demo72=lazy(()=>import('../vendor/rare/demos/matrix-orb').then(m=>({default:m.default})));
const Demo73=lazy(()=>import('../vendor/rare/demos/animated-counter').then(m=>({default:m.default})));
const Demo74=lazy(()=>import('../vendor/shadcn/examples/field-demo').then(m=>({default:m.default})));
const Demo75=lazy(()=>import('../vendor/shadcn/examples/button-demo').then(m=>({default:m.default})));
const Demo76=lazy(()=>import('../vendor/shadcn/examples/button-group-demo').then(m=>({default:m.default})));
const Demo77=lazy(()=>import('../vendor/shadcn/examples/input-demo').then(m=>({default:m.default})));
const Demo78=lazy(()=>import('../vendor/shadcn/examples/input-group-demo').then(m=>({default:m.default})));
const Demo79=lazy(()=>import('../vendor/shadcn/examples/input-otp-demo').then(m=>({default:m.default})));
const Demo80=lazy(()=>import('../vendor/shadcn/examples/textarea-demo').then(m=>({default:m.default})));
const Demo81=lazy(()=>import('../vendor/shadcn/examples/checkbox-demo').then(m=>({default:m.default})));
const Demo82=lazy(()=>import('../vendor/shadcn/examples/radio-group-demo').then(m=>({default:m.default})));
const Demo83=lazy(()=>import('../vendor/shadcn/examples/select-demo').then(m=>({default:m.default})));
const Demo84=lazy(()=>import('../vendor/shadcn/examples/native-select-demo').then(m=>({default:m.default})));
const Demo85=lazy(()=>import('../vendor/shadcn/examples/switch-demo').then(m=>({default:m.default})));
const Demo86=lazy(()=>import('../vendor/shadcn/examples/slider-demo').then(m=>({default:m.default})));
const Demo87=lazy(()=>import('../vendor/shadcn/examples/calendar-demo').then(m=>({default:m.default})));
const Demo88=lazy(()=>import('../vendor/shadcn/examples/date-picker-demo').then(m=>({default:m.default})));
const Demo89=lazy(()=>import('../vendor/shadcn/examples/combobox-demo').then(m=>({default:m.default})));
const Demo90=lazy(()=>import('../vendor/shadcn/examples/label-demo').then(m=>({default:m.default})));
const Demo91=lazy(()=>import('../vendor/shadcn/examples/accordion-demo').then(m=>({default:m.default})));
const Demo92=lazy(()=>import('../vendor/shadcn/examples/breadcrumb-demo').then(m=>({default:m.default})));
const Demo93=lazy(()=>import('../vendor/shadcn/examples/navigation-menu-demo').then(m=>({default:m.default})));
const Demo94=lazy(()=>import('../vendor/shadcn/internal/sidebar-demo').then(m=>({default:m.default})));
const Demo95=lazy(()=>import('../vendor/shadcn/examples/tabs-demo').then(m=>({default:m.default})));
const Demo96=lazy(()=>import('../vendor/shadcn/examples/separator-demo').then(m=>({default:m.default})));
const Demo97=lazy(()=>import('../vendor/shadcn/examples/scroll-area-demo').then(m=>({default:m.default})));
const Demo98=lazy(()=>import('../vendor/shadcn/examples/resizable-demo').then(m=>({default:m.default})));
const Demo99=lazy(()=>import('../vendor/shadcn/examples/dialog-demo').then(m=>({default:m.default})));
const Demo100=lazy(()=>import('../vendor/shadcn/examples/alert-dialog-demo').then(m=>({default:m.default})));
const Demo101=lazy(()=>import('../vendor/shadcn/examples/sheet-demo').then(m=>({default:m.default})));
const Demo102=lazy(()=>import('../vendor/shadcn/examples/drawer-demo').then(m=>({default:m.default})));
const Demo103=lazy(()=>import('../vendor/shadcn/examples/popover-demo').then(m=>({default:m.default})));
const Demo104=lazy(()=>import('../vendor/shadcn/examples/tooltip-demo').then(m=>({default:m.default})));
const Demo105=lazy(()=>import('../vendor/shadcn/examples/hover-card-demo').then(m=>({default:m.default})));
const Demo106=lazy(()=>import('../vendor/shadcn/examples/context-menu-demo').then(m=>({default:m.default})));
const Demo107=lazy(()=>import('../vendor/shadcn/examples/dropdown-menu-demo').then(m=>({default:m.default})));
const Demo108=lazy(()=>import('../vendor/shadcn/examples/menubar-demo').then(m=>({default:m.default})));
const Demo109=lazy(()=>import('../vendor/shadcn/examples/command-demo').then(m=>({default:m.default})));
const Demo110=lazy(()=>import('../vendor/shadcn/examples/alert-demo').then(m=>({default:m.default})));
const Demo111=lazy(()=>import('../vendor/shadcn/examples/sonner-demo').then(m=>({default:m.default})));
const Demo112=lazy(()=>import('../vendor/shadcn/examples/sonner-demo').then(m=>({default:m.default})));
const Demo113=lazy(()=>import('../vendor/shadcn/examples/progress-demo').then(m=>({default:m.default})));
const Demo114=lazy(()=>import('../vendor/shadcn/examples/spinner-demo').then(m=>({default:m.default})));
const Demo115=lazy(()=>import('../vendor/shadcn/examples/skeleton-demo').then(m=>({default:m.default})));
const Demo116=lazy(()=>import('../vendor/shadcn/examples/badge-demo').then(m=>({default:m.default})));
const Demo117=lazy(()=>import('../vendor/shadcn/examples/empty-demo').then(m=>({default:m.default})));
const Demo118=lazy(()=>import('../vendor/shadcn/examples/avatar-demo').then(m=>({default:m.default})));
const Demo119=lazy(()=>import('../vendor/shadcn/examples/card-demo').then(m=>({default:m.default})));
const Demo120=lazy(()=>import('../vendor/shadcn/examples/table-demo').then(m=>({default:m.default})));
const Demo121=lazy(()=>import('../vendor/shadcn/examples/data-table-stable-demo').then(m=>({default:m.default})));
const Demo122=lazy(()=>import('../vendor/shadcn/charts/chart-bar-default').then(m=>({default:m.ChartBarDefault})));
const Demo123=lazy(()=>import('../vendor/shadcn/examples/carousel-demo').then(m=>({default:m.default})));
const Demo124=lazy(()=>import('../vendor/shadcn/examples/aspect-ratio-demo').then(m=>({default:m.default})));
const Demo125=lazy(()=>import('../vendor/shadcn/examples/typography-demo').then(m=>({default:m.default})));
const Demo126=lazy(()=>import('../vendor/shadcn/examples/item-demo').then(m=>({default:m.default})));
const Demo127=lazy(()=>import('../vendor/shadcn/examples/kbd-demo').then(m=>({default:m.default})));
const Demo128=lazy(()=>import('../vendor/shadcn/examples/collapsible-demo').then(m=>({default:m.default})));
const Demo129=lazy(()=>import('../vendor/shadcn/examples/toggle-demo').then(m=>({default:m.default})));
const Demo130=lazy(()=>import('../vendor/shadcn/examples/toggle-group-demo').then(m=>({default:m.default})));
const Demo131=lazy(()=>import('../vendor/shadcn/examples/pagination-demo').then(m=>({default:m.default})));
const foundationDemos: Record<string,ComponentType<{dark?:boolean}>>={
"interior:hold-to-confirm": Demo0,
"interior:loading-button": Demo1,
"interior:ripple": Demo2,
"interior:floating-label": Demo3,
"interior:press-depth": Demo4,
"interior:icon-morph": Demo5,
"interior:like-burst": Demo6,
"interior:copy-button": Demo7,
"interior:password-strength": Demo8,
"interior:expanding-search": Demo9,
"interior:inline-validation": Demo10,
"interior:otp-input": Demo11,
"interior:tag-input": Demo12,
"interior:progress-bar": Demo13,
"interior:skeleton-swap": Demo14,
"interior:load-more": Demo15,
"interior:task-steps": Demo16,
"interior:live-activity": Demo17,
"interior:collapsible-banner": Demo18,
"interior:presence-avatars": Demo19,
"interior:streaming-text": Demo20,
"interior:typing-indicator": Demo21,
"interior:modal": Demo22,
"interior:new-items-pill": Demo23,
"interior:context-menu": Demo24,
"interior:drawer": Demo25,
"interior:tooltip-group": Demo26,
"interior:dropdown": Demo27,
"interior:command-palette": Demo28,
"interior:popover": Demo29,
"interior:segmented-control": Demo30,
"interior:tabs": Demo31,
"interior:sticky-header": Demo32,
"interior:tree-view": Demo33,
"interior:pagination": Demo34,
"interior:reading-progress": Demo35,
"interior:scroll-spy": Demo36,
"interior:accordion": Demo37,
"interior:wizard-steps": Demo38,
"interior:snap-carousel": Demo39,
"interior:filter-grid": Demo40,
"interior:hide-on-scroll": Demo41,
"interior:value-flash": Demo42,
"interior:reorder-list": Demo43,
"interior:poll-results": Demo44,
"interior:swipe-deck": Demo45,
"interior:slider-detents": Demo46,
"interior:sortable-table": Demo47,
"interior:long-press": Demo48,
"interior:logo-marquee": Demo49,
"interior:blur-up-image": Demo50,
"interior:lightbox": Demo51,
"interior:text-reveal": Demo52,
"rare:folder-component": ()=><PreviewControlsProvider><Demo53/></PreviewControlsProvider>,
"interior:show-more": Demo54,
"rare:hook-sidebar": ()=><PreviewControlsProvider><Demo55/></PreviewControlsProvider>,
"rare:proximity-sidebar": ()=><PreviewControlsProvider><Demo56/></PreviewControlsProvider>,
"rare:fluid-orb": ()=><PreviewControlsProvider><Demo57/></PreviewControlsProvider>,
"rare:family-drawer": ()=><PreviewControlsProvider><Demo58/></PreviewControlsProvider>,
"rare:code-block": ()=><PreviewControlsProvider><Demo59/></PreviewControlsProvider>,
"rare:scroll-progress": ()=><PreviewControlsProvider><Demo60/></PreviewControlsProvider>,
"rare:duration-picker": ()=><PreviewControlsProvider><Demo61/></PreviewControlsProvider>,
"rare:bounce-sidebar": ()=><PreviewControlsProvider><Demo62/></PreviewControlsProvider>,
"rare:gravity-letters": ()=><PreviewControlsProvider><Demo63/></PreviewControlsProvider>,
"rare:emoji-reaction": ()=><PreviewControlsProvider><Demo64/></PreviewControlsProvider>,
"rare:notification-bell": ()=><PreviewControlsProvider><Demo65/></PreviewControlsProvider>,
"rare:otp-input": ()=><PreviewControlsProvider><Demo66/></PreviewControlsProvider>,
"rare:gooey-nav": ()=><PreviewControlsProvider><Demo67/></PreviewControlsProvider>,
"rare:step-player": ()=><PreviewControlsProvider><Demo68/></PreviewControlsProvider>,
"rare:github-activity": ()=><PreviewControlsProvider><Demo69/></PreviewControlsProvider>,
"rare:grid-reveal": ()=><PreviewControlsProvider><Demo70/></PreviewControlsProvider>,
"rare:delete-button": ()=><PreviewControlsProvider><Demo71/></PreviewControlsProvider>,
"rare:matrix-orb": ()=><PreviewControlsProvider><Demo72/></PreviewControlsProvider>,
"rare:animated-counter": ()=><PreviewControlsProvider><Demo73/></PreviewControlsProvider>,
"shadcn:field": ()=><Demo74/>,
"shadcn:button": ()=><Demo75/>,
"shadcn:button-group": ()=><Demo76/>,
"shadcn:input": ()=><Demo77/>,
"shadcn:input-group": ()=><Demo78/>,
"shadcn:input-otp": ()=><Demo79/>,
"shadcn:textarea": ()=><Demo80/>,
"shadcn:checkbox": ()=><Demo81/>,
"shadcn:radio-group": ()=><Demo82/>,
"shadcn:select": ()=><Demo83/>,
"shadcn:native-select": ()=><Demo84/>,
"shadcn:switch": ()=><Demo85/>,
"shadcn:slider": ()=><Demo86/>,
"shadcn:calendar": ()=><Demo87/>,
"shadcn:date-picker": ()=><Demo88/>,
"shadcn:combobox": ()=><Demo89/>,
"shadcn:label": ()=><Demo90/>,
"shadcn:accordion": ()=><Demo91/>,
"shadcn:breadcrumb": ()=><Demo92/>,
"shadcn:navigation-menu": ()=><Demo93/>,
"shadcn:sidebar": ()=><Demo94/>,
"shadcn:tabs": ()=><Demo95/>,
"shadcn:separator": ()=><Demo96/>,
"shadcn:scroll-area": ()=><Demo97/>,
"shadcn:resizable": ()=><Demo98/>,
"shadcn:dialog": ()=><Demo99/>,
"shadcn:alert-dialog": ()=><Demo100/>,
"shadcn:sheet": ()=><Demo101/>,
"shadcn:drawer": ()=><Demo102/>,
"shadcn:popover": ()=><Demo103/>,
"shadcn:tooltip": ()=><Demo104/>,
"shadcn:hover-card": ()=><Demo105/>,
"shadcn:context-menu": ()=><Demo106/>,
"shadcn:dropdown-menu": ()=><Demo107/>,
"shadcn:menubar": ()=><Demo108/>,
"shadcn:command": ()=><Demo109/>,
"shadcn:alert": ()=><Demo110/>,
"shadcn:toast": ({dark})=><><Demo111/><Toaster theme={dark ? "dark" : "light"}/></>,
"shadcn:sonner": ({dark})=><><Demo112/><Toaster theme={dark ? "dark" : "light"}/></>,
"shadcn:progress": ()=><Demo113/>,
"shadcn:spinner": ()=><Demo114/>,
"shadcn:skeleton": ()=><Demo115/>,
"shadcn:badge": ()=><Demo116/>,
"shadcn:empty": ()=><Demo117/>,
"shadcn:avatar": ()=><Demo118/>,
"shadcn:card": ()=><Demo119/>,
"shadcn:table": ()=><Demo120/>,
"shadcn:data-table": ()=><Demo121/>,
"shadcn:chart": ()=><Demo122/>,
"shadcn:carousel": ()=><Demo123/>,
"shadcn:aspect-ratio": ()=><Demo124/>,
"shadcn:typography": ()=><Demo125/>,
"shadcn:item": ()=><Demo126/>,
"shadcn:kbd": ()=><Demo127/>,
"shadcn:collapsible": ()=><Demo128/>,
"shadcn:toggle": ()=><Demo129/>,
"shadcn:toggle-group": ()=><Demo130/>,
"shadcn:pagination": ()=><Demo131/>,
'rare:utils':()=> <div className="space-y-3 text-sm"><p>Class name utility</p><code>{cn('px-2 bg-stone-100','px-4 rounded-lg')}</code><p>Combines conditional classes and resolves Tailwind conflicts.</p></div>,
'shadcn:direction':()=> <DirectionProvider dir="rtl"><div dir="rtl" className="flex gap-4 rounded-lg border p-6"><span>مرحبا</span><span>العالم</span></div></DirectionProvider>
};

// Official shadcn examples expect the application-level tooltip context.
export const previews: Record<string, ComponentType<{dark?:boolean}>> = Object.fromEntries(
  Object.entries(foundationDemos).map(([id, Preview]) => [
    id,
    id.startsWith('shadcn:')
      ? function ShadcnPreview(props: {dark?:boolean}) {
          return <TooltipProvider><Preview {...props}/></TooltipProvider>;
        }
      : Preview,
  ]),
);
