import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {dirname} from 'node:path';import {createHash} from 'node:crypto';
const exec=promisify(execFile);const cat=JSON.parse(readFileSync('src/data/catalog.json','utf8')).filter(e=>e.library==='coss');const manifest={imports:[],dependencies:[],covered:[],blocked:[]};const dependencies=new Set();const seen=new Map();
async function get(url){return (await exec('curl',['-fsSL','--retry','2','--max-time','35',url],{maxBuffer:20e6})).stdout}
function save(p,s){mkdirSync(dirname(p),{recursive:true});writeFileSync(p,s)}
async function registry(name){if(seen.has(name))return seen.get(name);const task=(async()=>{const url=`https://coss.com/ui/r/${name}.json`;let data;try{data=JSON.parse(await get(url))}catch(e){throw new Error(`${name}: ${e.message}`)}for(const d of data.dependencies||[])dependencies.add(d);for(const f of data.files||[]){if(!f.content)continue;let path=f.path.replace(/^registry\/default\//,'');const output=`src/vendor/coss/${path}`;let content=f.content.replaceAll('@/registry/default/','@/vendor/coss/').replaceAll('@/lib/','@/vendor/coss/lib/');save(output,content);manifest.imports.push({library:'coss',name,url,file:output,sha256:createHash('sha256').update(f.content).digest('hex'),modifications:'Import aliases only',dependencies:data.dependencies||[]})}await Promise.all((data.registryDependencies||[]).filter(d=>d.startsWith('@coss/')).map(d=>registry(d.slice(6))));return data})();seen.set(name,task);return task}
let lines=[];for(let offset=0;offset<cat.length;offset+=6){await Promise.all(cat.slice(offset,offset+6).map(async e=>{if(['label','sidebar'].includes(e.slug))return;const name=`p-${e.slug}-1`;try{const data=await registry(name);const f=data.files.find(f=>f.path.includes('/particles/'));if(!f)throw new Error('No particle file');const path=f.path.replace(/^registry\/default\//,'').replace(/\.tsx$/,'');lines.push(`'${e.id}':lazy(()=>import('../vendor/coss/${path}')),`);manifest.covered.push(e.id);console.log(e.slug)}catch(err){manifest.blocked.push({id:e.id,reason:err.message});console.log('blocked',e.slug)}}))}
await registry('label');await registry('sidebar');await registry('input');
lines.push(`'coss:label':()=> <div className="space-y-2"><Label htmlFor="coss-label">Email address</Label><Input id="coss-label" placeholder="you@example.com"/></div>,`);
lines.push(`'coss:sidebar':()=> <SidebarProvider><Sidebar collapsible="none" className="h-72"><SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarMenu>{['Overview','Projects','Settings'].map(t=><SidebarMenuItem key={t}><SidebarMenuButton>{t}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent></Sidebar></SidebarProvider>,`);manifest.covered.push('coss:label','coss:sidebar');
save('src/previews/coss.tsx',`import {lazy,type ComponentType} from 'react';\nimport {Label} from '../vendor/coss/ui/label';\nimport {Input} from '../vendor/coss/ui/input';\nimport {SidebarProvider,Sidebar,SidebarContent,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '../vendor/coss/ui/sidebar';\nexport const previews:Record<string,ComponentType<{dark?:boolean}>>={${lines.join('\n')}};`);
let generated=readFileSync('src/previews/coss.tsx','utf8').replace('export const previews:', 'const originalPreviews:');
generated='import {ToastProvider} from "../vendor/coss/ui/toast";\nimport {TooltipProvider} from "../vendor/coss/ui/tooltip";\n'+generated;
generated+='\nexport const previews:Record<string,ComponentType<{dark?:boolean}>>=Object.fromEntries(Object.entries(originalPreviews).map(([id,Demo])=>[id,(props:{dark?:boolean})=><TooltipProvider><ToastProvider><Demo {...props}/></ToastProvider></TooltipProvider>]));\n';
save('src/previews/coss.tsx',generated);
manifest.dependencies=[...dependencies];save('src/data/integrations/coss.json',JSON.stringify(manifest,null,2));save('public/licenses/coss.txt',readFileSync('research/coss-license.txt','utf8'));save('research/coss-globals.css',await get('https://raw.githubusercontent.com/cosscom/coss/main/apps/ui/app/globals.css'));
